"""First Migration

Revision ID: 0d44a98bc318
Revises: 3d7dedbc156a
Create Date: 2023-06-13 20:13:46.762307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d44a98bc318'
down_revision = '3d7dedbc156a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openweather_city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city')
    )
    op.create_index(op.f('ix_openweather_city_id'), 'openweather_city', ['id'], unique=False)
    op.create_table('openweather_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('atm_pressure', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('record_time', sa.DateTime(), nullable=True),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['city_name'], ['openweather_city.city'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_openweather_info_id'), 'openweather_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_openweather_info_id'), table_name='openweather_info')
    op.drop_table('openweather_info')
    op.drop_index(op.f('ix_openweather_city_id'), table_name='openweather_city')
    op.drop_table('openweather_city')
    # ### end Alembic commands ###
