"""First Migration

Revision ID: 5f38e54b4708
Revises: 99cece9b3dc9
Create Date: 2023-06-13 20:18:28.443373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f38e54b4708'
down_revision = '99cece9b3dc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
