"""First Migration

Revision ID: 99cece9b3dc9
Revises: 0d44a98bc318
Create Date: 2023-06-13 20:14:18.674808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99cece9b3dc9'
down_revision = '0d44a98bc318'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
