"""First Migration

Revision ID: acdf0b4b3072
Revises: 5f38e54b4708
Create Date: 2023-06-13 20:18:47.374603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acdf0b4b3072'
down_revision = '5f38e54b4708'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
