"""First Migration

Revision ID: db5068c1af7e
Revises: b368d578f30c
Create Date: 2023-06-15 19:12:12.786442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5068c1af7e'
down_revision = 'b368d578f30c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
